### ISSUE TITLE
Joder aquí no hay nada

### ISSUE THREAD

**Issue by alexbertis** [Diegox6/diegox6.github.io#1]
- la barra de navegación no funciona
- página sosa
- los links cuando están visitados no se ven bien
- la frase tonta no es como la del Minecraft, no rebota hacia alante y hacia atrás y no está torcida

**Comment by Diegox6** [comment]
Le notifico, querido usuario, que sí, esta pagina es, ciertamente, una mierda.

**Comment by alexbertis** [comment]
Solicito reabrir este issue debido a que existe un pull request #2 que solventa parte de los problemas
